export default {
  Array: 10,
  Binary: 5,
  'Binary Search': 1,
  'Binary Search Tree': 4,
  'Binary Tree': 8,
  'Dynamic Programming': 14,
  Graph: 8,
  'Hash Table': 2,
  Heap: 4,
  Interval: 5,
  'Linked List': 7,
  Matrix: 4,
  Stack: 2,
  String: 10,
  Trie: 5,
  Tree: 1,
};
